/* License generated by licensor(https://github.com/Marvin9/licensor).

 alexm622/tetris-ncurses
 Copyright (C) 2021  Alexander Comeau
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef BLOCKS_H
#define BLOCKS_H
#include <stdbool.h>
extern bool iBlock[1][4];
/**
 * @brief an enum of all the block types
 * 
 */
typedef enum{
    I,O,T,S,Z,L,J
}BLOCK;
/**
 * @brief the pixel object
 * 
 */
typedef struct pixel{
    bool empty;
    int x; /** the x position of the pixel*/
    int y; /** the y position of the pixel*/
}Pixel;
/**
 * @brief the block object
 * 
 */
typedef struct block{
    BLOCK b; /** the block enum name*/
    int num_pixels; /** the number of pixels in the block object */ // this might be unecessary, as it'll always be for
    Pixel ** pixels; /** all the pixels in the block */
}Block;
/**
 * @brief the whole playfield
 * 
 */
typedef struct playfield{
    Pixel *** field; /** a 2d array of pixel projects */
    int height; /** the height of the playfield*/
    int width; /** the width of the playfield*/
}Playfield;

Block initBlock(BLOCK b_type);
Pixel ** initL();
Pixel ** initJ();
Pixel ** initI();
Pixel ** initS();
Pixel ** initZ();
Pixel ** initO();
Pixel ** initT();

BLOCK blockGenerator();

void freeBlockElements(Block * b);
void freePlayfield(Playfield* p);
#endif