/* License generated by licensor(https://github.com/Marvin9/licensor).

 alexm622/tetris-ncurses
 Copyright (C) 2021  Alexander Comeau
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef GUI_H
#define GUI_H
#define WIDTH 20 
#define HEIGHT 20
#define XOFF 60
#define YOFF 2

#include <blocks.h>
#include <curses.h>

WINDOW* draw_gui();
void draw_block(Block b);
void draw_pixel(Pixel * p);
void draw_playfield(Playfield * pf);
void draw_score(int score);
Playfield * initialize_playfield(int width, int height);
#endif
